[wokwi]
version = 1
firmware = "src/main.ino"  # Ruta relativa desde la raíz

[env]
board = "esp32-devkit-c-v4"
framework = "arduino"
monitor_speed = 115200

[libraries]
WiFi = "*"
WebServer = "*"
NTPClient = "*"
ESP32Servo = "*"