[wokwi]
version = 1
firmware = "main/main.ino"

[env]
board = "esp32-devkit-c-v4"
framework = "arduino"
monitor_speed = 115200

[libraries]
ESP32Servo = "1.1.0"
WiFi = "2.0.0"
WebServer = "2.1.0"
NTPClient = "3.2.0"